services:
  mongo:
    image: mongo
    container_name: mongo-container-menu
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: crisPez
      MONGO_INITDB_ROOT_PASSWORD: dataMongo123
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: